### ISSUE TITLE
Depends on codeception ~2.1.0

### ISSUE THREAD

**Issue by AlexStansfield** [mcustiel/codeception-http-mock#2]
We're trying to upgrade to codeception 2.2 but we heavily rely on your library.

Is it incompatible with 2.2 or is this just a matter of updating the depencency in the composer.json of this project?

**Comment by mcustiel** [comment]
Hi. It is not tested on 2.2, but it should still work. I can not check it for the next 7 hours, since I am at work, if you could check it with codeception 2.2 it would be great :)

**Comment by mcustiel** [comment]
Hi. 
I modified composer file to allow installation of codeception 2.2.

**Comment by mcustiel** [comment]
Hi @AlexStansfield, I will close this issue assuming it is OK for you now. Please consider [Phiremock](https://github.com/mcustiel/phiremock) if you are needing a more complete way of mocking your external services.

**Comment by AlexStansfield** [comment]
sorry for the delay, thanks :)

**Comment by AlexStansfield** [comment]
I was just trying to upgrade this in one of my projects that runs on php 5.5.x.

I noticed when you updated the composer.json to allow support for codeception 2.2.x you also bumped the internations/http-mock version to ^0.8. Unfortunately 0.8+ requires php 5.6+ which prevented me updating.

Just wondered if this release really needed to go to http-mock 0.8+. I realise that 5.5 is now end of life but the most recent official ubuntu LTS available on AWS is still 14.04 which is rocking php 5.5.9.

**Comment by AlexStansfield** [comment]
No worries, took your advice and moved to Phiremock. Much nicer.
