### ISSUE TITLE
improper __destruct() in Codeception\Extension\HttpMock

### ISSUE THREAD

**Issue by JiankangMai** [mcustiel/codeception-http-mock#4]
I receive a failure that "Address is already in use".
I  trace some code,found extensions(like Codeception\Extension\HttpMock) of codeception was instantiated more than once(each suite start  and the global test  boot).And you just clean the http-mock in the uncontrollable __destruct();
Now I fixed  it   by following  code.and  it   run correctly now;
```
public static $events = [
        Events::SUITE_BEFORE => 'startHttpMock',
        Events::SUITE_AFTER  => 'stopHttpMock'
    ];

```
Perhaps it's because I use codeception2.2.7,not 2.1.*  ?

**Comment by mcustiel** [comment]
Thank you very much.
Fixed in version 0.7
